project:
  type: website

website:
  title: "ResearchSite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ProgressMonitoring_Districts.qmd
      - ResearchInsights.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute:
  freeze: auto


editor: visual

